# Generated by Django 2.2.8 on 2020-12-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmezapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(default='', max_length=50)),
                ('mrp_price', models.FloatField()),
                ('price', models.FloatField()),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('digital', models.NullBooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
